version: '3'
services:
  db:
    build:
        context: ./db/
        dockerfile: Dockerfile
    environment:
      POSTGRES_DB: trustarea
      POSTGRES_USER: trustarea
      POSTGRES_PASSWORD: trustarea
    restart: always
    networks:
      internal:
        aliases:
          - trustarea-db

  redis:
    image: redis:5.0.5
    ports:
      - "7379:6379"
    entrypoint: redis-server --appendonly yes
    restart: always
    networks:
      internal:
        aliases:
          - trustarea-redis

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - redis
    networks:
      internal:
        aliases:
          - trustarea-api

  proxy:
    image: nginx:alpine
    ports:
      - "7000:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./apk/:/apk/
      - ./logs/nginx/:/logs/
    depends_on:
      - api
    networks:
      internal:
        aliases:
          - trustarea-proxy

networks:
    internal:
